[package]

name = "fixed_size_array"
version = "0.0.1"
authors = ["Keegan McAllister <mcallister.keegan@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/kmcallister/fixed-size-array"
readme = "README.md"
description = "Trait for working with fixed size arrays"
